import { getEnv } from "../utils/getEnv";

export const appConfig = {
    NODE_ENV:getEnv("NODE_ENV"),
    PORT:getEnv("PORT","8951"),
    BASE_PATH:getEnv("BASE_PATH","/api"),
    SESSION_SECRET:getEnv("SESSION_SECRET"),
    GOOGLE_CLIENT_ID:getEnv("GOOGLE_CLIENT_ID"),
    GOOGLE_CLIENT_SECRET:getEnv("GOOGLE_CLIENT_SECRET"),
    GOOGLE_CALLBACK_URL:getEnv("GOOGLE_CALLBACK_URL"),
    FRONTEND_ORIGIN:getEnv("FRONTEND_ORIGIN"),
    FRONTEND_GOOGLE_CALLBACK_URL:getEnv("FRONTEND_GOOGLE_CALLBACK_URL"),
    JWT_ACCESS_TOKEN_SECRET:getEnv("JWT_ACCESS_TOKEN_SECRET"),
    JWT_REFRESH_TOKEN_SECRET:getEnv("JWT_REFRESH_TOKEN_SECRET"),
    REDIS_URL:getEnv("REDIS_URL"),
    RESEND_API_KEY:getEnv("RESEND_API_KEY"),
}